public interface PatternNamesConstants {
    public static final String[] NAMES = {
        "Accordion",
        "Headerless Menu",
        "Breadcrumbs",
        "Directory Navigation",
        "Doormat Navigation",
        "Double Tab Navigation",
        "Faceted Navigation",
        "Fly-out Menu",
        "Home Link",
        "Icon Menu",
        "Main Navigation",
        "Map Navigator",
        "Meta Navigation",
        "Minesweeping",
        "Panning Navigator",
        "Overlay Menu",
        "Repeated Menu",
        "Retractable Menu",
        "Scrolling Menu",
        "Shortcut Box",
        "Split Navigation",
        "Teaser Menu",
        "To-the-top Link",
        "Trail Menu",
        "Navigation Tree",
        "Action Button",
        "Guided Tour",
        "Paging",
        "Pulldown Button",
        "Slideshow",
        "Stepping",
        "Wizard",
        "Advanced Search",
        "Autocomplete",
        "Frequently Asked Questions (FAQ)",
        "Help Wizard",
        "Search Box",
        "Search Area",
        "Search Results",
        "Search Tips",
        "Site Index",
        "Site Map",
        "Footer Sitemap",
        "Tag Cloud",
        "Topic Pages",
        "Carrousel",
        "Table Filter",
        "Collapsible Panels",
        "Details On Demand",
        "Collector",
        "Inplace replacement",
        "List Builder",
        "List Entry View",
        "Overview by Detail",
        "Parts Selector",
        "Tabs",
        "Table Sorter",
        "Thumbnail",
        "View",
        "Customizable Window",
        "Login",
        "Registration",
        "Booking",
        "Product Comparison",
        "Product Advisor",
        "Product Configurator",
        "Purchase Process",
        "Shopping Cart",
        "Store Locator",
        "Testimonials",
        "Virtual Product Display",
        "Country Selector",
        "Date Selector",
        "Language Selector",
        "Poll",
        "Rating",
        "Comment Box",
        "Constraint Input",
        "Form",
        "Footer Bar",
        "Hotlist",
        "News Box",
        "News Ticker",
        "Send-a-Friend Link",
        "Captcha",
        "Center Stage",
        "Color Coded Section",
        "Premium Content Lock",
        "Grid-based Layout",
        "Liquid Layout",
        "Outgoing Links",
        "Alternating Row Colors",
        "Input Error Message",
        "Processing Page",
        "Enlarged Clickarea",
        "Font Enlarger",
        "Web-based Application",
        "Artist Site",
        "Automotive Site",
        "Branded Promotion Site",
        "Campaign Site",
        "E-commerce Site",
        "Community Site",
        "Corporate Site",
        "Multinational Site",
        "Museum Site",
        "Personalized 'My' Site",
        "News Site",
        "Portal Site",
        "Travel Site",
        "Community Building",
        "Information Management",
        "Fun",
        "Information Seeking",
        "Learning",
        "Assistence",
        "Shopping",
        "Story Telling",
        "Article Page",
        "Blog Page",
        "Case Study",
        "Contact Page",
        "Event Calendar",
        "Forum",
        "Guest Book",
        "Help Page",
        "Homepage",
        "Newsletter",
        "Printer-friendly Page",
        "Product Page",
        "Tutorial",
        "Image Browser"
    };

    public static String fromNumber(int number) {
        return NAMES[number - 1];
    }
}
